apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-application
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hharshas/argocd-app:3.0
        ports:
        - containerPort: 8080
